Scoreboard_title: '&3&lHCRealms &7| &fKits'
Kitmap:
  Sharpness: 1
  Protection: 1
kits-mode: true
block-in-combat: true
SERVER_NAME: HCRealms
DONATE_URL: store.hcrealms.us
SPAWN_NO_BREAK_RADIUS: 150
WARZONE_RADIUS: 150
NETHER_WARZONE_RADIUS: 300
MAX-FACTION: 25
MAX-ALLY: 0
DEFAULT_DEATHBAN_DURATION: 3600000
WILDERNESS_COLOUR: DARK_GREEN
WARZONE_COLOUR: RED
SAFEZONE_COLOUR: AQUA
TEAMMATE_COLOUR: DARK_GREEN
ALLY_COLOUR: BLUE
ENEMY_COLOUR: RED
ROAD_COLOUR: GOLD
GLOWSTONE_COLOUR: GOLD
COMBATLOG_DESPAWN_DELAY_TICKS: 300
potionLimits:
  STRENGTH: 0
  INVISIBILITY: 1
  REGEN: 0
  WEAKNESS: 0
  INSTANT_DAMAGE: 0
  SLOWNESS: 1
  POISON: 1
potionsExtendedDisallowed:
  POISON
  SLOWNESS
Help:
- '&8&m------------------------------------'
- '&3&lMap Infomation&7:'
- '&7Current Map&8 - &fMap 1'
- '&7Map Border&8 - &f3000'
- '&7Map Kit&8 - &f/mapkit'
- '&8&m------------------------------------'
- '&3&lUseful Commands&7:'
- '&7/coords - &fProvides the coordinates for KoTH Locations'
- '&7/teamspeak - &fProvides the Teamspeak Server IP'
- '&7/rules - &cCurrently Disabled &7(https://hcrealms.us/forums/rules/)'
- '&7/mapkit - &fProvides you with the Map Information on Enchant Limits and Potions'
- '&7/report <Player> <Reason> - &fA command to report rule-breakers'
- '&7/helpop <Message> - &fAlerts online Staff Members that you are in need of
  assistance'
- '&8&m------------------------------------'
- '&3&lOther infomation&7:'
- '&7Website&8 - &fwww.hcrealms.us'
- '&7Buycraft&8 - &fstore.hcrealms.us'
- '&7Teamspeak&8 - &fts.hcrealms.us'
- '&8&m------------------------------------'
Teamspeak:
- '&7Teamspeak: &fts.hcrealms.us'
teamspeak-frozen: ts.hcrealms.us
Coords:
- '&8&m----------------------------------------'
- '&6&lCoords'
- '&eSpawn: &70,0 &7(Overworld)'
- '&eNether Spawn: &70,0 &7(Nether)'
- '&eEndPortals: &70,1500,0 &7(All for quads)'
- '&8&m----------------------------------------'
spawn:
  world: world
  x: 0.538049846829157
  y: 69.0
  z: 0.6617853658512408
  yaw: 0.78689575
  pitch: 11.715501
